In [2]:
from bs4 import BeautifulSoup
import pandas as pd 
import numpy as np
import requests

In [ ]:
df = pd.read_csv('df_Advanced.csv', sep = ',', header=[0,1], index_col =0)

# Preprocessing Data 

In [ ]:
df.head()

In [ ]:
df.sort_values(by = [('Infomation', 'Date')])
df.drop("Rk", level=1, axis=1, inplace=True)
df.reset_index(drop=True, inplace=True)

df[('Predictor','R')] = 0
df[('Predictor','PTS')] = 0
df[('Predictor','PTSA')]= 0

In [ ]:

for i in range(len(df)):
    print('row: ' + str(i))
    r, points = (df.loc[i,[('Infomation', 'Result')]][0]).split()
    PTS, PTSA = points.split('-')
    df.loc[[i],[('Predictor', 'R')]], df.loc[[i],[('Predictor', 'PTS')]], df.loc[[i],[('Predictor', 'PTSA')]] = r, PTS, PTSA


In [ ]:
df.dropna(axis=0, inplace=True)
df.reset_index(drop=True, inplace=True)

In [ ]:
df.to_csv('df_Advanced_clean.csv', sep = ',')

In [108]:
df = pd.read_csv('df_Advanced_clean.csv', sep = ',', header=[0,1], index_col =0)

In [109]:
df[('Predictor', 'R')] = (df[('Predictor', 'R')] == 'W').astype(int)

In [110]:
df.sort_values(by = [('Infomation', 'Date')], inplace =True)
df.reset_index(drop=True, inplace=True)

In [113]:
df.head()

Infomation                                  Team                       \
         Date   Tm Home/Away  Opp     Result   ORtg    FTr   3PAr    TS%   
0  1983-10-28  CLE         0  NYK  L 106-113  116.8  0.513  0.038  0.554   
1  1983-10-28  WSB         1  PHI  L 114-117  110.1  0.354  0.024  0.602   
2  1983-10-28  PHI         0  WSB  W 117-114  113.0  0.512  0.000  0.582   
3  1983-10-28  UTA         1  DEN  L 125-139  115.6  0.320  0.020  0.548   
4  1983-10-28  DEN         0  UTA  W 139-125  128.6  0.382  0.000  0.583   

         ...  Opponent        Differnces                              \
    eFG% ...       TS%   eFG%       ORtg    FTr   3PAr    TS%   eFG%   
0  0.513 ...     0.617  0.590       -7.7  0.115 -0.038 -0.062 -0.077   
1  0.561 ...     0.582  0.512       -2.9 -0.159  0.024  0.019  0.049   
2  0.512 ...     0.602  0.561        2.9  0.159 -0.024 -0.019 -0.049   
3  0.500 ...     0.583  0.539      -12.9 -0.062  0.020 -0.035 -0.039   
4  0.539 ...     0.548  0.500       12.9  0.062 -0.020  0.035  0.039   

  Predictor            
          R  PTS PTSA  
0         0  106  113  
1         0  114  117  
2         1  117  114  
3         0  125  139  
4         1  139  125  

[5 rows x 23 columns]

In [114]:
df_CLE = df.where(df.loc[:, ('Infomation', 'Tm')] == 'CLE')

In [115]:
df_CLE.dropna(axis=0, inplace=True)
df_CLE.reset_index(drop=True, inplace=True)

In [116]:
df[('Infomation', 'Date')] = pd.to_datetime(df[('Infomation', 'Date')])

In [119]:
df_date = df_CLE.loc[:, [('Infomation', 'Date')]]
df_CLE = pd.concat([df_date, df_CLE.loc[:, ['Team', 'Opponent', 'Differnces', 'Predictor']]], axis=1, sort=False)
df_CLE.columns = df_CLE.columns.droplevel()
    

In [152]:
df_CLE_ =pd.DataFrame()
l = []
for i in range(3, len(df_CLE)):
    row = (
      [df_CLE.iloc[i, 0]]
    + df_CLE.iloc[i-3,1:-3].tolist()
    + df_CLE.iloc[i-2,1:-3].tolist()
    + df_CLE.iloc[i-1,1:-3].tolist()
    + df_CLE.iloc[i,-3:].tolist())
    l.append(row)

In [153]:
df_CLE_ = pd.DataFrame(l)

In [184]:

columns =  ['Date',
           'ORtg1.1', 'FTr1.1', '3PAr1.1', 'TS%1.1', 'eFG%1.1',
           'ORtg1.2', 'FTr1.2', '3PAr1.2', 'TS%1.2', 'eFG%1.2',
           'ORtg1.3', 'FTr1.3', '3PAr1.3', 'TS%1.3', 'eFG%1.3',
           'ORtg2.1', 'FTr2.1', '3PAr2.1', 'TS%2.1', 'eFG%2.1',
           'ORtg2.2', 'FTr2.2', '3PAr2.2', 'TS%2.2', 'eFG%2.2',
           'ORtg2.3', 'FTr2.3', '3PAr2.3', 'TS%2.3', 'eFG%2.3',           
           'ORtg3.1', 'FTr3.1', '3PAr3.1', 'TS%3.1', 'eFG%3.1',
           'ORtg3.2', 'FTr3.2', '3PAr3.2', 'TS%3.2', 'eFG%3.2',
           'ORtg3.3', 'FTr3.3', '3PAr3.3', 'TS%3.3', 'eFG%3.3',
            'R', 'PTS', 'PTSA']

df_CLE_.columns = columns

In [187]:
from sklearn.model_selection import train_test_split
#from sklearn.preprocessing import StandardScaler

In [188]:
#sc_X = StandardScaler()
#X_std = sc_X.fit_transform(X)

In [234]:
y = df_CLE_['R']
y = y.values.reshape(1, -1).flatten()
X = df_CLE_.drop(['Date', 'R', 'PTS', 'PTSA'], axis=1)

In [239]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1) 

In [236]:
#from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
#import xgboost as xgb

In [237]:
clf_LR = LogisticRegression()

In [193]:
clf_LR.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [240]:
from sklearn.model_selection import cross_val_score, cross_val_predict
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [241]:
def print_score(clf, X_train, y_train, X_test, y_test, train=True):
    '''
    print the accuracy score, classification report and confusion matrix of classifier
    '''
    if train:
        '''
        training performance
        '''
        print("Train Result:\n")
        print("accuracy score: {0:.4f}\n".format(accuracy_score(y_train, clf.predict(X_train))))
        print("Classification Report: \n {}\n".format(classification_report(y_train, clf.predict(X_train))))
        print("Confusion Matrix: \n {}\n".format(confusion_matrix(y_train, clf.predict(X_train))))

        res = cross_val_score(clf, X_train, y_train, cv=10, scoring='accuracy')
        print("Average Accuracy: \t {0:.4f}".format(np.mean(res)))
        print("Accuracy SD: \t\t {0:.4f}".format(np.std(res)))
        
    elif train==False:
        '''
        test performance
        '''
        print("Test Result:\n")        
        print("accuracy score: {0:.4f}\n".format(accuracy_score(y_test, clf.predict(X_test))))
        print("Classification Report: \n {}\n".format(classification_report(y_test, clf.predict(X_test))))
        print("Confusion Matrix: \n {}\n".format(confusion_matrix(y_test, clf.predict(X_test))))  

In [196]:
print_score(clf_LR, X_train, y_train, X_test, y_test, train=True)

Train Result:

accuracy score: 0.5843

Classification Report: 
              precision    recall  f1-score   support

        0.0       0.57      0.54      0.56       894
        1.0       0.59      0.63      0.61       956

avg / total       0.58      0.58      0.58      1850


Confusion Matrix: 
 [[480 414]
 [355 601]]

Average Accuracy: 	 0.5664
Accuracy SD: 		 0.0237


In [197]:
print_score(clf_LR, X_train, y_train, X_test, y_test, train=False)

Test Result:

accuracy score: 0.5718

Classification Report: 
              precision    recall  f1-score   support

        0.0       0.60      0.55      0.57       416
        1.0       0.55      0.60      0.57       378

avg / total       0.57      0.57      0.57       794


Confusion Matrix: 
 [[228 188]
 [152 226]]



In [242]:
from datetime import datetime

from sklearn.model_selection import RandomizedSearchCV, GridSearchCV
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import StratifiedKFold
from xgboost import XGBClassifier

In [224]:
def timer(start_time=None):
    if not start_time:
        start_time = datetime.now()
        return start_time
    elif start_time:
        thour, temp_sec = divmod((datetime.now() - start_time).total_seconds(), 3600)
        tmin, tsec = divmod(temp_sec, 60)
        print('\n Time taken: %i hours %i minutes and %s seconds.' % (thour, tmin, round(tsec, 2)))

In [225]:
params = {
        'min_child_weight': [1, 5, 10],
        'gamma': [0.5, 1, 1.5, 2, 5],
        'subsample': [0.6, 0.8, 1.0],
        'colsample_bytree': [0.6, 0.8, 1.0],
        'max_depth': [3, 4, 5]
        }

In [226]:
xgb = XGBClassifier(learning_rate=0.02, n_estimators=600, objective='binary:logistic',
                    silent=True, nthread=1)

In [227]:
folds = 3
param_comb = 5

skf = StratifiedKFold(n_splits=folds, shuffle = True, random_state = 1001)

random_search = RandomizedSearchCV(xgb, param_distributions=params, n_iter=param_comb, scoring='roc_auc', n_jobs=4, cv=skf.split(X,y), verbose=3, random_state=1001 )

# Here we go
start_time = timer(None) # timing starts from this point for "start_time" variable
random_search.fit(X, y)
timer(start_time) # timing ends here for "start_time" variable

Fitting 3 folds for each of 5 candidates, totalling 15 fits


[Parallel(n_jobs=4)]: Done  15 out of  15 | elapsed:   34.4s finished



 Time taken: 0 hours 0 minutes and 39.98 seconds.


In [228]:
print('\n All results:')
print(random_search.cv_results_)
print('\n Best estimator:')
print(random_search.best_estimator_)
print('\n Best normalized gini score for %d-fold search with %d parameter combinations:' % (folds, param_comb))
print(random_search.best_score_ * 2 - 1)
print('\n Best hyperparameters:')
print(random_search.best_params_)
results = pd.DataFrame(random_search.cv_results_)
results.to_csv('xgb-random-grid-search-results-01.csv', index=False)


 All results:
{'mean_fit_time': array([4.81135162, 8.90316224, 8.6664203 , 6.40477467, 7.61180957]), 'std_fit_time': array([0.11045593, 0.01151809, 0.133682  , 0.14735791, 0.24954798]), 'mean_score_time': array([0.05456614, 0.08130169, 0.08453488, 0.04292051, 0.04882868]), 'std_score_time': array([0.05733059, 0.0013712 , 0.02498349, 0.00382561, 0.0014759 ]), 'param_subsample': masked_array(data=[1.0, 0.6, 0.8, 1.0, 0.8],
             mask=[False, False, False, False, False],
       fill_value='?',
            dtype=object), 'param_min_child_weight': masked_array(data=[5, 1, 5, 5, 1],
             mask=[False, False, False, False, False],
       fill_value='?',
            dtype=object), 'param_max_depth': masked_array(data=[3, 5, 5, 5, 4],
             mask=[False, False, False, False, False],
       fill_value='?',
            dtype=object), 'param_gamma': masked_array(data=[5, 1.5, 1, 5, 1],
             mask=[False, False, False, False, False],
       fill_value='?',
            dt

C:\Users\Nikhil\AppData\Local\conda\conda\envs\MachineLearningTutorials\lib\site-packages\sklearn\utils\deprecation.py:122: FutureWarning: You are accessing a training score ('split0_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
C:\Users\Nikhil\AppData\Local\conda\conda\envs\MachineLearningTutorials\lib\site-packages\sklearn\utils\deprecation.py:122: FutureWarning: You are accessing a training score ('split1_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
C:\Users\Nikhil\AppData\Local\conda\conda\envs\MachineLearningTutorials\lib\site-packages\sklearn\utils\deprecation.py:122: FutureWarning: You are accessing a training score ('split2_train_score'), which will not be available by default any more in 0.21. If you need training 

In [229]:
grid = GridSearchCV(estimator=xgb, param_grid=params, scoring='roc_auc', n_jobs=-1, cv=skf.split(X,y), verbose=3 )
grid.fit(X, y)
print('\n All results:')
print(grid.cv_results_)
print('\n Best estimator:')
print(grid.best_estimator_)
print('\n Best score:')
print(grid.best_score_ * 2 - 1)
print('\n Best parameters:')
print(grid.best_params_)
results = pd.DataFrame(grid.cv_results_)
results.to_csv('xgb-grid-search-results-01.csv', index=False)

y_test = grid.best_estimator_.predict_proba(X_test)
results_df = pd.DataFrame(data={'id':test_df['id'], 'target':y_test[:,1]})
results_df.to_csv('submission-grid-search-xgb-porto-01.csv', index=False)

Fitting 3 folds for each of 405 candidates, totalling 1215 fits


[Parallel(n_jobs=4)]: Done  24 tasks      | elapsed:   40.5s
[Parallel(n_jobs=4)]: Done 120 tasks      | elapsed:  3.0min
[Parallel(n_jobs=4)]: Done 280 tasks      | elapsed:  6.8min
[Parallel(n_jobs=4)]: Done 504 tasks      | elapsed: 11.8min
[Parallel(n_jobs=4)]: Done 792 tasks      | elapsed: 18.4min
[Parallel(n_jobs=4)]: Done 1144 tasks      | elapsed: 28.5min
[Parallel(n_jobs=4)]: Done 1215 out of 1215 | elapsed: 30.5min finished



 All results:
{'mean_fit_time': array([ 4.37275441,  4.41748063,  4.40473851,  4.63310393,  4.18888958,
        3.93181443,  4.30186955,  4.14607779,  3.93765243,  5.86725092,
        5.80542032,  5.39283037,  5.68557358,  5.65266577,  5.30942734,
        5.47579797,  5.53091828,  5.23759516,  7.45659407,  7.46152083,
        6.89303923,  7.07757497,  7.1264267 ,  6.75797097,  6.77386316,
        6.93131097,  6.5953486 ,  4.43451095,  4.50114417,  4.09453932,
        4.52234975,  4.28930918,  3.97078482,  4.24387701,  4.23342999,
        3.95325589,  5.85306334,  5.80686784,  5.39596216,  5.69078374,
        5.67431291,  5.33933091,  5.52808301,  5.58603549,  5.24654587,
        7.45162559,  7.45016789,  6.93739875,  7.11477439,  7.14409272,
        6.86349829,  6.78703014,  6.93999108,  6.62610515,  4.3689359 ,
        4.40684676,  3.84553035,  4.10573355,  4.30845682,  3.99831867,
        4.27217038,  4.18977785,  3.84205715,  5.70110949,  5.70394556,
        5.16682307,  5.4564515 

C:\Users\Nikhil\AppData\Local\conda\conda\envs\MachineLearningTutorials\lib\site-packages\sklearn\utils\deprecation.py:122: FutureWarning: You are accessing a training score ('split0_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
C:\Users\Nikhil\AppData\Local\conda\conda\envs\MachineLearningTutorials\lib\site-packages\sklearn\utils\deprecation.py:122: FutureWarning: You are accessing a training score ('split1_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
C:\Users\Nikhil\AppData\Local\conda\conda\envs\MachineLearningTutorials\lib\site-packages\sklearn\utils\deprecation.py:122: FutureWarning: You are accessing a training score ('split2_train_score'), which will not be available by default any more in 0.21. If you need training 

NameError: name 'test' is not defined

In [232]:
grid.best_estimator_

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=0.6, gamma=5, learning_rate=0.02, max_delta_step=0,
       max_depth=3, min_child_weight=5, missing=None, n_estimators=600,
       n_jobs=1, nthread=1, objective='binary:logistic', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=True, subsample=1.0)

In [231]:
y_test = grid.best_estimator_.predict_proba(X_test)
#results_df = pd.DataFrame(data={'id':test_df['id'], 'target':y_test[:,1]})
#results_df.to_csv('submission-grid-search-xgb-porto-01.csv', index=False)

In [243]:
print_score(grid.best_estimator_, X_train, y_train, X_test, y_test, train=True)
print_score(grid.best_estimator_, X_train, y_train, X_test, y_test, train=False)

Train Result:

accuracy score: 0.6931

Classification Report: 
              precision    recall  f1-score   support

        0.0       0.70      0.67      0.68      1175
        1.0       0.69      0.71      0.70      1204

avg / total       0.69      0.69      0.69      2379


Confusion Matrix: 
 [[791 384]
 [346 858]]



C:\Users\Nikhil\AppData\Local\conda\conda\envs\MachineLearningTutorials\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\Users\Nikhil\AppData\Local\conda\conda\envs\MachineLearningTutorials\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\Users\Nikhil\AppData\Local\conda\conda\envs\MachineLearningTutorials\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\Users\Nikhil\AppData\Loca

Average Accuracy: 	 0.5679
Accuracy SD: 		 0.0259
Test Result:

accuracy score: 0.6717

Classification Report: 
              precision    recall  f1-score   support

        0.0       0.70      0.63      0.66       135
        1.0       0.65      0.72      0.68       130

avg / total       0.67      0.67      0.67       265


Confusion Matrix: 
 [[85 50]
 [37 93]]



C:\Users\Nikhil\AppData\Local\conda\conda\envs\MachineLearningTutorials\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\Users\Nikhil\AppData\Local\conda\conda\envs\MachineLearningTutorials\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\Users\Nikhil\AppData\Local\conda\conda\envs\MachineLearningTutorials\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\Users\Nikhil\AppData\Loca