In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('teamdf1000games.csv', sep=',', index_col = 0)

In [3]:
df.drop(['index', 'Result', 'Rk', 'Date','Tm', 'Opp'], axis=1, inplace= True)

In [4]:
#cols = ['Tm', 'Opp']
#df = pd.get_dummies(df, columns = cols)

In [5]:
df = df[df.MP.apply(lambda x: x.isnumeric())]

In [6]:
df.head()

MP  FG  FGA   FG%  2P 2PA   2P%  3P 3PA   3P%  ...  2P.1 2PA.1 2P%.1 3P.1  \
0  240  46  102  .451  40  78  .513   6  24  .250  ...    26    51  .510   11   
1  240  37   91  .407  26  51  .510  11  40  .275  ...    40    78  .513    6   
2  240  32   86  .372  21  52  .404  11  34  .324  ...    32    54  .593   15   
3  240  47   89  .528  32  54  .593  15  35  .429  ...    21    52  .404   11   
4  240  37   94  .394  31  70  .443   6  24  .250  ...    31    58  .534   12   

  3PA.1 3P%.1 FT.1 FTA.1  FT%.1 PTS.1  
0    40  .275   12    16   .750    97  
1    24  .250   12    15   .800   110  
2    35  .429   10    10  1.000   119  
3    34  .324   12    18   .667    87  
4    27  .444   12    13   .923   110  

[5 rows x 27 columns]

In [7]:
df.columns.values

array(['MP', 'FG', 'FGA', 'FG%', '2P', '2PA', '2P%', '3P', '3PA', '3P%',
       'FT', 'FTA', 'FT%', 'PTS', 'FG.1', 'FGA.1', 'FG%.1', '2P.1',
       '2PA.1', '2P%.1', '3P.1', '3PA.1', '3P%.1', 'FT.1', 'FTA.1',
       'FT%.1', 'PTS.1'], dtype=object)

In [8]:
df = df.astype(float)

In [9]:
df ['W/L'] = np.sign(df["PTS"] - df["PTS.1"])


In [10]:
df.head()

MP    FG    FGA    FG%    2P   2PA    2P%    3P   3PA    3P% ...   \
0  240.0  46.0  102.0  0.451  40.0  78.0  0.513   6.0  24.0  0.250 ...    
1  240.0  37.0   91.0  0.407  26.0  51.0  0.510  11.0  40.0  0.275 ...    
2  240.0  32.0   86.0  0.372  21.0  52.0  0.404  11.0  34.0  0.324 ...    
3  240.0  47.0   89.0  0.528  32.0  54.0  0.593  15.0  35.0  0.429 ...    
4  240.0  37.0   94.0  0.394  31.0  70.0  0.443   6.0  24.0  0.250 ...    

   2PA.1  2P%.1  3P.1  3PA.1  3P%.1  FT.1  FTA.1  FT%.1  PTS.1  W/L  
0   51.0  0.510  11.0   40.0  0.275  12.0   16.0  0.750   97.0  1.0  
1   78.0  0.513   6.0   24.0  0.250  12.0   15.0  0.800  110.0 -1.0  
2   54.0  0.593  15.0   35.0  0.429  10.0   10.0  1.000  119.0 -1.0  
3   52.0  0.404  11.0   34.0  0.324  12.0   18.0  0.667   87.0  1.0  
4   58.0  0.534  12.0   27.0  0.444  12.0   13.0  0.923  110.0 -1.0  

[5 rows x 28 columns]

In [11]:
df['PTS'] = df['PTS']/240
df['FG'] = df['FG']/240
df['FGA'] = df['FGA']/240
df['2P'] = df['2P']/240
df['2PA'] = df['2PA']/240
df['3P'] = df['3P']/240
df['3PA'] = df['3PA']/240
df['FT'] = df['FT']/240
df['FTA'] = df['FTA']/240
df['PTS.1'] = df['PTS.1']/240
df['FG.1'] = df['FG.1']/240
df['FGA.1'] = df['FGA.1']/240
df['2P.1'] = df['2P.1']/240
df['2PA.1'] = df['2PA.1']/240
df['3P.1'] = df['3P.1']/240
df['3PA.1'] = df['3PA.1']/240
df['FT.1'] = df['FT.1']/240
df['FTA.1'] = df['FTA.1']/240

In [12]:
df = df.drop('MP', axis=1)

In [13]:
df.dropna(axis = 0, inplace=True)

In [14]:
#df.to_csv('teamdf1000games_cleaned.csv', sep = ',')

In [15]:
y = df['W/L']
y = y.values.reshape(1, -1).flatten()

X = df.drop("W/L", axis=1)

In [16]:
from sklearn.model_selection import train_test_split
#from sklearn.preprocessing import StandardScaler

In [17]:
#sc_X = StandardScaler()
#X_std = sc_X.fit_transform(X)

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3) 

In [19]:
#from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
#import xgboost as xgb

In [20]:
clf_LR = LogisticRegression()

In [21]:
clf_LR.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [22]:
from sklearn.model_selection import cross_val_score, cross_val_predict
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [23]:
def print_score(clf, X_train, y_train, X_test, y_test, train=True):
    '''
    print the accuracy score, classification report and confusion matrix of classifier
    '''
    if train:
        '''
        training performance
        '''
        print("Train Result:\n")
        print("accuracy score: {0:.4f}\n".format(accuracy_score(y_train, clf.predict(X_train))))
        print("Classification Report: \n {}\n".format(classification_report(y_train, clf.predict(X_train))))
        print("Confusion Matrix: \n {}\n".format(confusion_matrix(y_train, clf.predict(X_train))))

        res = cross_val_score(clf, X_train, y_train, cv=10, scoring='accuracy')
        print("Average Accuracy: \t {0:.4f}".format(np.mean(res)))
        print("Accuracy SD: \t\t {0:.4f}".format(np.std(res)))
        
    elif train==False:
        '''
        test performance
        '''
        print("Test Result:\n")        
        print("accuracy score: {0:.4f}\n".format(accuracy_score(y_test, clf.predict(X_test))))
        print("Classification Report: \n {}\n".format(classification_report(y_test, clf.predict(X_test))))
        print("Confusion Matrix: \n {}\n".format(confusion_matrix(y_test, clf.predict(X_test))))  

In [24]:
print_score(clf_LR, X_train, y_train, X_test, y_test, train=True)

Train Result:

accuracy score: 0.9804

Classification Report: 
              precision    recall  f1-score   support

       -1.0       0.98      0.98      0.98     24155
        1.0       0.98      0.98      0.98     24173

avg / total       0.98      0.98      0.98     48328


Confusion Matrix: 
 [[23670   485]
 [  462 23711]]

Average Accuracy: 	 0.9789
Accuracy SD: 		 0.0020


In [25]:
print_score(clf_LR, X_train, y_train, X_test, y_test, train=False)

Test Result:

accuracy score: 0.9796

Classification Report: 
              precision    recall  f1-score   support

       -1.0       0.98      0.98      0.98     10346
        1.0       0.98      0.98      0.98     10367

avg / total       0.98      0.98      0.98     20713


Confusion Matrix: 
 [[10133   213]
 [  210 10157]]



In [26]:
df_test = pd.read_csv('teamdf_playoff_games.csv', sep=',', index_col = 0)

df_test.drop(['index', 'Result', 'Rk', 'Date','Tm', 'Opp'], axis=1, inplace= True)
#cols = ['Tm', 'Opp']
#df = pd.get_dummies(df, columns = cols)

df_test = df_test[df_test.MP.apply(lambda x: x.isnumeric())]
df_test = df_test.astype(float)
df_test ['W/L'] = np.sign(df_test["PTS"] - df_test["PTS.1"])


In [27]:
df_test['PTS'] = df_test['PTS']/240
df_test['FG'] = df_test['FG']/240
df_test['FGA'] = df_test['FGA']/240
df_test['2P'] = df_test['2P']/240
df_test['2PA'] = df_test['2PA']/240
df_test['3P'] = df_test['3P']/240
df['3PA'] = df['3PA']/240
df_test['FT'] = df_test['FT']/240
df_test['FTA'] = df_test['FTA']/240
df_test['PTS.1'] = df_test['PTS.1']/240
df_test['FG.1'] = df_test['FG.1']/240
df_test['FGA.1'] = df_test['FGA.1']/240
df_test['2P.1'] = df_test['2P.1']/240
df_test['2PA.1'] = df_test['2PA.1']/240
df_test['3P.1'] = df_test['3P.1']/240
df_test['3PA.1'] = df_test['3PA.1']/240
df_test['FT.1'] = df_test['FT.1']/240
df_test['FTA.1'] = df_test['FTA.1']/240

df_test = df_test.drop('MP', axis=1)

df_test.dropna(axis = 0, inplace=True)

#df.to_csv('teamdf1000games_cleaned.csv', sep = ',')

y_t = df_test['W/L']
y_t = y_t.values.reshape(1, -1).flatten()

X_t = df_test.drop("W/L", axis=1)

In [28]:
print("Test Result:\n")        
print("accuracy score: {0:.4f}\n".format(accuracy_score(y_t, clf_LR.predict(X_t))))
print("Classification Report: \n {}\n".format(classification_report(y_t, clf_LR.predict(X_t))))
print("Confusion Matrix: \n {}\n".format(confusion_matrix(y_t, clf_LR.predict(X_t))))

Test Result:

accuracy score: 0.4959

Classification Report: 
              precision    recall  f1-score   support

       -1.0       0.00      0.00      0.00       489
        1.0       0.50      1.00      0.66       481

avg / total       0.25      0.50      0.33       970


Confusion Matrix: 
 [[  0 489]
 [  0 481]]



C:\Users\Nikhil\AppData\Local\conda\conda\envs\MachineLearningTutorials\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
